# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Courtney Hannon'
tagline: 'Courtney Hannon, Humble Pie Signs'
description: 'Owner of Humble Pie Signs'

# Images
avatar: 'avatar.jpg'
background: 'il_1140xN.2616547519_ngcv.jpg'
favicon: 'isla_280x280_44770865_3kwx446q_zPY_icon.ico'

# Online profiles
facebook: 'courtney.hannon.946'
instagram: 'humblepiesigns'
pinterest: 'chann89'
etsy: 'humblepiesigns'
email: 'humblepiesigns@gmail.com'
sms: '301-536-1049'

social-links-order: [etsy, instagram, phone, pintrest, facebook, email]

# Advanced settings
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**
social-links:
  - name: facebook
    url-pattern: facebook.com/__USERNAME__
    icon-class: fab fa-2x fa-facebook-f

  - name: instagram
    url-pattern: instagram.com/__USERNAME__

  - name: pinterest
    url-pattern: pinterest.com/__USERNAME__
    
  - name: etsy
    url-pattern: __USERNAME__.etsy.com
  
  - name: sms
    url-scheme: 'sms:'
    url-pattern: '__USERNAME__?body=Humble%20Pie%Signs%20look%20amazing%20'

  - name: email
    url-scheme: 'mailto:'
    url-pattern: '__USERNAME__'
    icon-class: far fa-2x fa-envelope-open
