# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Courtney Hannon'
tagline: 'Courtney Hannon, Humble Pie Signs'
description: 'Owner of Humble Pie Signs'

# Images
avatar: 'avatar.jpg'
background: 'il_1140xN.2616547519_ngcv.jpg'
favicon: 'isla_280x280_44770865_3kwx446q_zPY_icon.ico'

# Online profiles
Facebook: 'courtney.hannon.946'
Instagram: 'humblepiesigns'
Pinterest: 'chann89'
Etsy: 'humblepiesigns'
Email: 'humblepiesigns@gmail.com'
SMS: '301-536-1049'

social-links-order: [Etsy, Instagram, Pinterest, Facebook, SMS, Email]

# Advanced settings
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

social-links:
  - name: Facebook
    url-pattern: facebook.com/__USERNAME__
    icon-class: fab fa-2x fa-facebook-f

  - name: Instagram
    url-pattern: instagram.com/__USERNAME__
    icon-class: fab fa-2x fa-instagram

  - name: Pinterest
    url-pattern: pinterest.com/__USERNAME__
    icon-class: fab fa-2x fa-pinterest-p
    
  - name: Etsy
    url-pattern: __USERNAME__.etsy.com
    icon-class: fab fa-2x fa-etsy
  
  - name: SMS
    url-scheme: 'sms:'
    url-pattern: __USERNAME__?body=Hi%20Courtney!%20Your%20signs%20look%20amazing!
    icon-class: fas fa-2x fa-sms

  - name: Email
    url-pattern: mailto:__USERNAME__
    icon-class: far fa-2x fa-envelope-open
